services:
  app:
    build:
      context: ./master
      target: prod
      dockerfile: Dockerfile
    volumes:
      - ./master/:/app 
      - /app/node_modules  # ignores node_modules local to avoid conflits
    command: node launcher.js "${HEADLESS_TOKEN}"]
    environment:
      HEADLESS_TOKEN: ${HEADLESS_TOKEN}